"""Färdiga mallar som visas på startsidan. Lägg gärna till egna i samma format."""

MALLAR = [
    {
        "titel": "Fotboll", "etikett": "Sport", "farg": "#16A36A", "punkt": "green",
        "text": "Svensk och internationell fotboll från sportsajter.",
        "bevakning": {
            "namn": "Fotbollsnyheter",
            "kallor": [
                ["BBC Football", "http://feeds.bbci.co.uk/sport/football/rss.xml", False],
                ["ESPN FC", "https://www.espn.com/espn/rss/soccer/news", False],
                ["The Guardian Football", "https://www.theguardian.com/football/rss", False],
                ["Fotbollsdirekt", "https://www.fotbolldirekt.se/rss", False],
                ["Marca", "https://e00-marca.uecdn.es/rss/portada.xml", False],
                ["Sky Sports Football", "https://www.skysports.com/rss/12040", False],
                ["SVT Sport", "https://www.svt.se/sport/rss.xml", True],
                ["Aftonbladet Sport", "https://rss.aftonbladet.se/rss2/small/pages/sections/sportbladet/", True],
                ["Expressen Sport", "https://feeds.expressen.se/sport", True],
                ["BBC Sport", "http://feeds.bbci.co.uk/sport/rss.xml", True],
                ["NRK Sport", "https://www.nrk.no/sport/toppsaker.rss", True],
            ],
            "nyckelord": ["fotboll*", "football", "soccer", "målskytt", "offside", "straffspark", "allsvenskan",
                          "superettan", "damallsvenskan", "champions league", "premier league", "la liga", "serie a",
                          "bundesliga", "ligue 1", "europa league", "conference league", "malmö ff", "ifk göteborg",
                          "ifk norrköping", "elfsborg", "häcken", "sirius", "mjällby", "kalmar ff", "degerfors",
                          "värnamo", "brommapojkarna", "gais", "halmstad", "örebro sk", "varbergs bois",
                          "real madrid", "barcelona", "atletico madrid", "liverpool", "manchester united",
                          "manchester city", "arsenal", "chelsea", "tottenham", "newcastle", "bayern münchen",
                          "borussia dortmund", "psg", "juventus", "ac milan", "inter milan", "napoli"],
            "tvetydiga_ord": ["aik", "djurgården", "hammarby"],
            "kontextord": ["fotboll", "allsvenskan", "superettan", "tränare", "mittfältare", "anfallare",
                           "försvarare", "målvakt", "straffspark", "offside", "seriematch", "bortamatch",
                           "hemmamatch", "poängtapp"],
            "kategoriord": ["fotboll", "football", "soccer"],
        },
    },
    {
        "titel": "AI", "etikett": "Teknik", "farg": "#6D4AFF", "punkt": "violet",
        "text": "AI-modeller, bolagen bakom dem och regleringen runt omkring.",
        "bevakning": {
            "namn": "AI-bevakning",
            "kallor": [
                ["TechCrunch AI", "https://techcrunch.com/category/artificial-intelligence/feed/", False],
                ["The Verge AI", "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml", False],
                ["MIT Technology Review AI", "https://www.technologyreview.com/topic/artificial-intelligence/feed", False],
                ["VentureBeat AI", "https://venturebeat.com/category/ai/feed/", False],
                ["BBC Technology", "http://feeds.bbci.co.uk/news/technology/rss.xml", True],
                ["The Guardian Technology", "https://www.theguardian.com/technology/rss", True],
                ["SVT Nyheter", "https://www.svt.se/nyheter/rss.xml", True],
                ["Hacker News", "https://hnrss.org/frontpage", True],
            ],
            "nyckelord": ["ai", "ai-*", "artificiell intelligens", "artificial intelligence", "generativ ai",
                          "generative ai", "chatgpt", "openai", "anthropic", "deepmind", "llm*", "språkmodell*",
                          "large language model*", "maskininlärning", "machine learning", "ai act", "copilot",
                          "mistral ai", "agi"],
            "tvetydiga_ord": ["claude", "gemini", "llama", "grok"],
            "kontextord": ["ai", "modell", "model", "chatbot", "openai", "anthropic", "google", "meta", "xai"],
            "kategoriord": ["artificial intelligence", "artificiell intelligens"],
        },
    },
    {
        "titel": "Ekonomi", "etikett": "Finans", "farg": "#E8871E", "punkt": "orange",
        "text": "Räntor, inflation, börsen och konjunkturen i Sverige och världen.",
        "bevakning": {
            "namn": "Ekonomibevakning",
            "kallor": [
                ["Dagens industri", "https://www.di.se/rss", False],
                ["SVT Ekonomi", "https://www.svt.se/nyheter/ekonomi/rss.xml", False],
                ["BBC Business", "http://feeds.bbci.co.uk/news/business/rss.xml", False],
                ["The Guardian Business", "https://www.theguardian.com/business/rss", False],
                ["CNBC", "https://www.cnbc.com/id/100003114/device/rss/rss.html", True],
                ["SVT Nyheter", "https://www.svt.se/nyheter/rss.xml", True],
            ],
            "nyckelord": ["ekonomi*", "inflation*", "styrränt*", "ränt*", "riksbank*", "börs*", "stockholmsbörsen",
                          "kpi", "bnp", "konjunktur*", "lågkonjunktur*", "recession", "arbetslöshet*", "kronan",
                          "kvartalsrapport*", "delårsrapport*", "bostadspris*", "interest rate*", "central bank*",
                          "stock market*", "economy", "gdp", "ecb", "federal reserve"],
            "tvetydiga_ord": ["fed"],
            "kontextord": ["ränta", "räntan", "rate", "inflation", "powell"],
            "kategoriord": ["ekonomi", "economy", "business", "näringsliv"],
        },
    },
]
